"""add currency and exchange to watchlist

Revision ID: 1399ba9e81b4
Revises: 97876414413d
Create Date: 2026-08-19 15:05:18.680610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1399ba9e81b4'
down_revision: Union[str, None] = '97876414413d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('watchlist', sa.Column('exchange', sa.String(), nullable=False))
    op.alter_column('watchlist', 'market_cap',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('watchlist', 'pe_ratio',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('watchlist', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlist', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('watchlist', 'pe_ratio',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('watchlist', 'market_cap',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('watchlist', 'exchange')
    op.drop_column('watchlist', 'currency')
    # ### end Alembic commands ###
