"""add_missing_columns

Revision ID: 38843e2f5051
Revises: e62de38aa3eb
Create Date: 2026-08-19 14:16:54.611245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38843e2f5051'
down_revision: Union[str, None] = 'e62de38aa3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('name', sa.String(), nullable=False))
    op.add_column('watchlist', sa.Column('market_cap', sa.Integer(), nullable=False))
    op.add_column('watchlist', sa.Column('pe_ratio', sa.Integer(), nullable=False))
    op.add_column('watchlist', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'price')
    op.drop_column('watchlist', 'pe_ratio')
    op.drop_column('watchlist', 'market_cap')
    op.drop_column('watchlist', 'name')
    # ### end Alembic commands ###
