name: Deploy Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd EquityTracker/backend
            git pull origin master
            docker stop equitytracker-container || true
            docker rm equitytracker-container || true
            docker build -t equitytracker-backend .
            docker run -d -p 8000:8000 -e FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} --name equitytracker-container equitytracker-backend
          EOF
